#!/usr/bin/env bash
# Generates the Cursor rules from the single source of truth (skills/engineering-standards/).
# Core -> alwaysApply rule. References -> one agent-requested rule (Cursor has no lazy file loading).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/skills/engineering-standards"
OUT="$ROOT/.cursor/rules"
mkdir -p "$OUT"

strip_frontmatter() { sed '1{/^---$/!q}; 1,/^---$/d' "$1"; }

{
  cat <<'HDR'
---
description: Non-negotiable engineering baseline — iron laws, right-sizing, YAGNI ladder, clean code, SOLID, git discipline, approval gates.
alwaysApply: true
---

<!-- GENERATED by scripts/build.sh from skills/engineering-standards/SKILL.md — do not edit. -->
HDR
  strip_frontmatter "$SRC/SKILL.md"
} > "$OUT/engineering-standards.mdc"

{
  cat <<'HDR'
---
description: Operational detail behind the engineering baseline. Read when debugging, writing tests, verifying completion, planning multi-step work, reviewing code, delegating to agents, or designing a core-tier module.
alwaysApply: false
---

<!-- GENERATED by scripts/build.sh from skills/engineering-standards/references/ — do not edit. -->

# Engineering Workflows
HDR
  for f in debugging tdd verification planning code-review delegation architecture; do
    printf '\n\n---\n\n'
    cat "$SRC/references/$f.md"
  done
} > "$OUT/engineering-workflows.mdc"

# check: the laws must survive the generation
for needle in "NO FIX WITHOUT ROOT CAUSE" "NO PRODUCTION CODE WITHOUT A FAILING TEST" "NO COMPLETION CLAIM WITHOUT FRESH EVIDENCE"; do
  grep -qF "$needle" "$OUT"/*.mdc || { echo "FAIL: missing '$needle' in generated rules" >&2; exit 1; }
done
grep -q "^# Clean Architecture" "$OUT/engineering-workflows.mdc" || { echo "FAIL: references not concatenated" >&2; exit 1; }

echo "ok: $(wc -l < "$OUT/engineering-standards.mdc") + $(wc -l < "$OUT/engineering-workflows.mdc") lines written to .cursor/rules/"
