#!/usr/bin/env bash
# Generates the Cursor rules and the VS Code / Copilot instruction files from the single
# source of truth (skills/engineering-standards/).
#   Cursor  -> .cursor/rules/*.mdc          (alwaysApply baseline + agent-requested workflows)
#   Copilot -> .github/copilot-instructions.md + .github/instructions/*.instructions.md
#   AGENTS.md -> thin pointer for every other agent that reads it
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/skills/engineering-standards"
OUT="$ROOT/.cursor/rules"
GH="$ROOT/.github"
mkdir -p "$OUT" "$GH/instructions"

strip_frontmatter() { sed '1{/^---$/!q}; 1,/^---$/d' "$1"; }

{
  cat <<'HDR'
---
description: Non-negotiable engineering baseline — iron laws, right-sizing, YAGNI ladder, clean code, SOLID, git discipline, approval gates.
alwaysApply: true
---

<!-- GENERATED by scripts/build.sh from skills/engineering-standards/SKILL.md — do not edit. -->
HDR
  strip_frontmatter "$SRC/SKILL.md"
} > "$OUT/engineering-standards.mdc"

{
  cat <<'HDR'
---
description: Operational detail behind the engineering baseline. Read when debugging, writing tests, verifying completion, planning multi-step work, reviewing code, delegating to agents, or designing a core-tier module.
alwaysApply: false
---

<!-- GENERATED by scripts/build.sh from skills/engineering-standards/references/ — do not edit. -->

# Engineering Workflows
HDR
  for f in debugging tdd verification planning code-review delegation architecture repo-memory; do
    printf '\n\n---\n\n'
    cat "$SRC/references/$f.md"
  done
} > "$OUT/engineering-workflows.mdc"

# ---------- VS Code / GitHub Copilot ----------
# Copilot has no lazy file loading either. Baseline is always-on; the workflows ship as one
# instruction file, and the reference table is rewritten to paths that exist in the target repo.
{
  cat <<'HDR'
<!-- GENERATED by scripts/build.sh from skills/engineering-standards/SKILL.md — do not edit. -->
HDR
  strip_frontmatter "$SRC/SKILL.md" \
    | sed 's#\([^/]\)references/#\1.claude/skills/engineering-standards/references/#g'
} > "$GH/copilot-instructions.md"

{
  cat <<'HDR'
---
applyTo: '**'
description: Operational detail behind the engineering baseline — debugging, TDD, verification, planning, code review, delegation, core-tier architecture.
---

<!-- GENERATED by scripts/build.sh from skills/engineering-standards/references/ — do not edit. -->

# Engineering Workflows
HDR
  for f in debugging tdd verification planning code-review delegation architecture repo-memory; do
    printf '\n\n---\n\n'
    cat "$SRC/references/$f.md"
  done
} > "$GH/instructions/engineering-workflows.instructions.md"

cat > "$ROOT/AGENTS.md" <<'HDR'
<!-- GENERATED by scripts/build.sh — do not edit. -->

# Agent Instructions

The engineering baseline for this repository is `.github/copilot-instructions.md` — read it before
writing any code. It is non-negotiable: three iron laws (root cause before fix, failing test before
production code, fresh evidence before any completion claim), a right-sizing gate, and a YAGNI
ladder.

Before touching code in this repository, read `docs/ARCHITECTURE.md` and `docs/MEMORY.md` if they
exist. A change that alters the structure updates `docs/ARCHITECTURE.md` in the same diff.

Operational detail lives in `.claude/skills/engineering-standards/references/`:

| File | Read when |
|---|---|
| `debugging.md` | Any bug or test failure — before proposing a fix |
| `tdd.md` | Before writing implementation code |
| `verification.md` | Before claiming anything is done, fixed, or passing |
| `planning.md` | Work spanning multiple files, sessions, or people |
| `code-review.md` | Requesting or receiving review of a diff |
| `delegation.md` | Dispatching subagents or working in parallel branches |
| `architecture.md` | Designing a core-tier module |
| `repo-memory.md` | Entering a repository, or recording a decision worth keeping |
HDR

# check: the laws must survive the generation
for needle in "NO FIX WITHOUT ROOT CAUSE" "NO PRODUCTION CODE WITHOUT A FAILING TEST" "NO COMPLETION CLAIM WITHOUT FRESH EVIDENCE"; do
  grep -qF "$needle" "$OUT"/*.mdc || { echo "FAIL: missing '$needle' in Cursor rules" >&2; exit 1; }
  grep -qrF "$needle" "$GH" || { echo "FAIL: missing '$needle' in Copilot instructions" >&2; exit 1; }
done
for f in "$OUT/engineering-workflows.mdc" "$GH/instructions/engineering-workflows.instructions.md"; do
  grep -q "^# Clean Architecture" "$f" || { echo "FAIL: references not concatenated into $f" >&2; exit 1; }
done
grep -q '\.claude/skills/engineering-standards/references/debugging\.md' "$GH/copilot-instructions.md" \
  || { echo "FAIL: reference paths not rewritten for Copilot" >&2; exit 1; }

echo "ok: cursor $(wc -l < "$OUT/engineering-standards.mdc")+$(wc -l < "$OUT/engineering-workflows.mdc") | copilot $(wc -l < "$GH/copilot-instructions.md")+$(wc -l < "$GH/instructions/engineering-workflows.instructions.md") | AGENTS.md"
